import os
path = os.getcwd()
path = os.path.join(path,'subroutine','icon')

icon_window = os.path.join(path,'Icon_Files','LogoWindow.png')
splash_screen = os.path.join(path,'Icon_Files','FIX\Splash Screen.png')
icon_graph = os.path.join(path,'Icon_Files','FIX\graph.ico')
icon_import = os.path.join(path,'Icon_Files','import.png')
icon_export = os.path.join(path,'Icon_Files','export.png')
icon_ascii = os.path.join(path,'Icon_Files','Mimetype-ascii-icon.png')
icon_slist = os.path.join(path,'Icon_Files','Checklist-icon.png')
icon_exit = os.path.join(path,'Icon_Files','Actions-application-exit-icon.png')
icon_merge = os.path.join(path,'Icon_Files','merge-icon.png')
icon_filter = os.path.join(path,'Icon_Files','Actions-view-filter-icon.png')
icon_envelope = os.path.join(path,'Icon_Files','envelope-icon.png')
icon_spectogram = os.path.join(path,'Icon_Files','document-frequency-icon.png')
icon_subwindows = os.path.join(path,'Icon_Files','Iconshock-Real-Vista-Multimedia-Audio-wave.ico')
icon_start = os.path.join(path,'Icon_Files','getting started1.png')
icon_locate = os.path.join(path,'Icon_Files','location.png')
icon_relocate = os.path.join(path,'Icon_Files','relocation.png')
icon_datasets = os.path.join(path,'Icon_Files','Document-Blank-icon.png')
getting_started = os.path.join(path,'Icon_Files','FIX\getting startedpic.png')
getting_started_bottom = os.path.join(path,'Icon_Files','FIX\getting started botton.png')
icon_tomo = os.path.join(path,'Icon_Files','Ocean-Waves-icon.png')

